language: python
python:
  - "2.7"

env:
  - DJANGO="django==1.8.17"
  - DJANGO="django==1.9.12"
  - DJANGO="django==1.10.5"
  - DJANGO="https://github.com/django/django/archive/master.tar.gz"

matrix:
  allow_failures:
    - env: DJANGO="https://github.com/django/django/archive/master.tar.gz"

install:
  - python setup.py install
  - pip install -r test_requirements.txt
  - pip install $DJANGO

before_script:
  - psql -c 'CREATE DATABASE django_pg_agefilter;' -U postgres

script:
  - coverage run --source=django_pg_agefilter runtests.py
  - coverage report -m
