language: python
python:
  - "2.7"

env:
  - DJANGO="django==1.5.12"
  - DJANGO="django==1.6.11"
  - DJANGO="django==1.7.11"
  - DJANGO="django==1.8.7"
  - DJANGO="django==1.9.2"
  - DJANGO="-e git+https://github.com/django/django.git@master#egg=django"

matrix:
  allow_failures:
    - env: DJANGO="-e git+https://github.com/django/django.git@master#egg=django"

install:
  - python setup.py install
  - pip install -r test_requirements.txt
  - pip install $DJANGO

before_script:
  - psql -c 'CREATE DATABASE django_pg_agefilter;' -U postgres

script:
  - coverage run --source=django_pg_agefilter runtests.py
  - coverage report -m
