language: python
python:
  - "2.7"

env:
  - DJANGO="django==1.6.8"
  - DJANGO="django==1.7.1"
  - DJANGO="-e git+https://github.com/django/django.git#egg=django"

install:
  - python setup.py -q install
  - pip install -r test_requirements.txt
  - pip install $DJANGO

script:
  - coverage run --source=django_pg_agefilter runtests.py
  - coverage report -m
